repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff format
        language: system
        types: [python]
      - id: ruff-lint
        name: Ruff Lint
        entry: uv run ruff check --fix --unsafe-fixes
        language: system
        types: [python]
      - id: pnpm-prettier
        name: Prettier
        entry: pnpm exec prettier --write
        language: system
        files: "\\.(?:[cm]?js|tsx?|json|ya?ml|md)$"
      - id: pnpm-eslint
        name: ESLint
        entry: pnpm exec eslint --fix --max-warnings 0 --no-warn-ignored
        language: system
        files: "\\.(?:ts|tsx)$"
